traefik:
  deployment:
    enabled: true

  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.faforever.localhost`)
      entryPoints: ["websecure", "web"]

  additionalArguments:
    - "--entrypoints.websecure.http.encodequerysemicolons=true"
    - "--entrypoints.web.http.encodequerysemicolons=true"

  updateStrategy:
    type: Recreate

  hostNetwork: false

  ports:
    metrics:
      # When using hostNetwork, use another port to avoid conflict with node exporter:
      # https://github.com/prometheus/prometheus/wiki/Default-port-allocations
      port: 9101

    web:
      transport:
        respondingTimeouts:
          readTimeout: 60
          
    websecure:
      transport:
        respondingTimeouts:
          readTimeout: 60

    replay-stream:
      port: 15000

  # HostNetwork
  service:
    enabled: true

  logs:
    general:
      # -- By default, the logs use a text format (common), but you can
      # also ask for the json format in the format option
      # format: json
      # By default, the level is set to ERROR.
      # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: INFO
    access:
      enabled: true
  
  providers:
    kubernetesCRD:
      allowExternalNameServices: true
