CONFIGURATION_REFRESH_TIME: 60
LOG_LEVEL: "INFO"

LISTEN:
  - ADDRESS:
    PORT: 8003
    PROTOCOL: SimpleJsonProtocol
    PROXY: true

DB_SERVER: "mariadb"
DB_LOGIN: "faf-python-server"
DB_NAME: "faf_lobby"

MQ_SERVER: "rabbitmq"
MQ_PORT: 5672
MQ_VHOST: "/faf-core"
MQ_USER: "faf-lobby-server"
MQ_EXCHANGE_NAME: "faf-lobby"

ENABLE_METRICS: true

FAF_POLICY_SERVER_BASE_URL: "http://faf-policy-server:8097"

FORCE_STEAM_LINK: "true"
# Seconds since epoch. 2018-09-15T12:00:00+00:00
FORCE_STEAM_LINK_AFTER_DATE: 0

USE_API: false

PROFILING_INTERVAL: 4
LADDER_ANTI_REPETITION_LIMIT: 1
ALLOW_PASSWORD_LOGIN: false
LADDER_1V1_OUTCOME_OVERRIDE: false

MAXIMUM_RATING_IMBALANCE: 250
MAXIMUM_RATING_DEVIATION: 250

TIME_BONUS: 0.01
NEWBIE_TIME_BONUS: .25
MAXIMUM_NEWBIE_TIME_BONUS: 3.0
MINORITY_BONUS: 1

QUEUE_POP_TIME_MAX: 90

# 3rd Jan 2026: Disable matchmaking bans
# There are problems with the ban system when a game doesn't start due to
# connection issues. The current hypothesis is that all players except for the
# match host receive a violation, regardless of whether they could establish
# connections successfully or not.
#
# The in-development Pioneer ICE Adapter is better in terms of initial
# connections. So the impact of the erroneous violations might become small
# enough to simpy accept it. Once Pioneer goes into prod we can think about
# reverting this.
LADDER_VIOLATIONS_ENABLED: false
