apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
{{- if .Values.hostIP }}
  clusterIP: None
  ports:
    - protocol: "TCP"
      port: {{.Values.port}}
      targetPort: {{.Values.port}}
{{ else }}
  type: ExternalName
  externalName: {{.Values.hostname}}
{{- end }}