image:
  repository: "oryd/hydra"
  tag: "v25.4.0"
infisical-secret:
  name: ory-hydra
clients:
  - name: "FAF Client"
    id: "2e8808cf-5889-469b-b2c3-01f0cc58c4af"
    grantType: "authorization_code,refresh_token"
    scope: "openid,email,offline,public_profile,lobby,upload_map,upload_mod"
    redirectUri: "http://127.0.0.1"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    tokenEndpointAuthMethod: "none"

  - name: "FAF Classic Client (Python)"
    id: "95ecec08-29c1-4c48-ae0a-b000ff349cb8"
    grantType: "authorization_code,refresh_token"
    scope: "openid,offline,lobby,public_profile"
    redirectUri: "http://localhost,http://127.0.0.1"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    tokenEndpointAuthMethod: "none"

  - name: "FAF Moderator Client"
    id: "8ff5c14f-60e2-41b9-b594-a641dc5013be"
    grantType: "authorization_code"
    scope: "openid,offline,public_profile,upload_avatar,administrative_actions,read_sensible_userdata,manage_vault"
    redirectUri: "http://localhost,http://localhost:8080/,http://127.0.0.1"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    clientUri: "https://github.com/FAForever/faf-moderator-client"
    tokenEndpointAuthMethod: "none"

  - name: "Ethereal FAF client"
    id: "b05039ed-e2ab-4fb6-8a7f-e6ecdcc2edcd"
    grantType: "authorization_code,refresh_token"
    scope: "openid,offline,public_profile,lobby,upload_map,upload_mod"
    redirectUri: "http://localhost,http://localhost:57728,http://localhost:59573,http://localhost:58256,http://localhost:53037,http://localhost:51360"
    logoUri: "https://raw.githubusercontent.com/Eternal-ll/Ethereal-FAF-Client/master/Logo/OAuth.svg"
    clientUri: "https://github.com/Eternal-ll/Ethereal-FAF-Client"
    tokenEndpointAuthMethod: "none"

  - name: "www.$BASE_DOMAIN"
    id: "c5613672-0ee5-4956-8b03-c7951ef25640"
    secret:
      name: faf-website
      key: OAUTH_CLIENT_SECRET
    skipConsent: true
    grantType: "authorization_code,refresh_token"
    scope: "openid,offline,public_profile,write_account_data"
    redirectUri: "https://www.$BASE_DOMAIN/callback,https://www.$BASE_DOMAIN/auth"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    clientUri: "https://github.com/FAForever/faf-moderator-client"
    tokenEndpointAuthMethod: "client_secret_post"

  - name: "FAF Website (public)"
    id: "b9f62a18-faae-43cc-a9b7-e15613e00273"
    secret:
      name: faf-website
      key: OAUTH_M2M_CLIENT_SECRET
    grantType: "client_credentials"
    scope: "public_profile"
    tokenEndpointAuthMethod: "client_secret_post"

  - name: "voting.$BASE_DOMAIN"
    id: "e3dfa9e8-93ad-4593-8b3c-900005439354"
    secret:
      name: faf-voting
      key: CLIENT_SECRET
    skipConsent: true
    grantType: "authorization_code,refresh_token"
    scope: "openid,public_profile"
    redirectUri: "https://wiki.$BASE_DOMAIN/login/9edbd0f7-b647-46dc-97c9-3a20293cd830/callback"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    tokenEndpointAuthMethod: "client_secret_post"

  - name: "forum.$BASE_DOMAIN"
    id: "97853a31-d7fc-424b-a4c2-f8cd053d10d2"
    secret:
      name: nodebb
      key: OAUTH_SECRET
    skipConsent: true
    grantType: "authorization_code,refresh_token"
    scope: "openid,email,public_profile,lobby"
    redirectUri: "https://forum.$BASE_DOMAIN/auth/faf-nodebb/callback"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    tokenEndpointAuthMethod: "client_secret_post"

  - name: "brackman-discord"
    id: "fbdc5ce5-9888-4ace-8ccc-378fbcb18992"
    secret:
      name: ory-hydra
      key: BRACKMAN_DISCORD_SECRET
    grantType: "client_credentials"
    scope: "public_profile"
    tokenEndpointAuthMethod: "client_secret_post"
    owner: "Paul Wayper"

  - name: "faf-qai"
    id: "5eecb64d-0f67-4a72-ac2b-717b8c7efa98"
    secret:
      name: ory-hydra
      key: FAF_QAI_SECRET
    grantType: "client_credentials"
    scope: "public_profile"
    tokenEndpointAuthMethod: "client_secret_post"

  - name: "FAF Wiki"
    id: "b44e0022-f6a7-41ec-b6c1-3932b00c88aa"
    secret:
      name: ory-hydra
      key: WIKIJS_SECRET
    grantType: "authorization_code,refresh_token"
    scope: "openid,public_profile"
    redirectUri: "https://wiki.$BASE_DOMAIN/login/hydra/callback"
    tosUri: "https://$BASE_DOMAIN/tos"
    policyUri: "https://$BASE_DOMAIN/privacy"
    logoUri: "https://$BASE_DOMAIN/images/faf-logo.png"
    tokenEndpointAuthMethod: "client_secret_post"
